// This file is generated by shiren6.py. Do not edit this file directly.
import type { Arrow } from './definitions';

export const arrows: readonly Arrow[] = [
    {
        id: "4001",
        type: "arrow",
        name: "木の矢",
        buyPrice: 10,
        sellPrice: 4,
        identificationStatus: "always",
    
    },
    {
        id: "4002",
        type: "arrow",
        name: "鉄の矢",
        buyPrice: 30,
        sellPrice: 12,
        identificationStatus: "always",
    
    },
    {
        id: "4003",
        type: "arrow",
        name: "銀の矢",
        buyPrice: 50,
        sellPrice: 20,
        identificationStatus: "always",
    
    },
    {
        id: "4004",
        type: "arrow",
        name: "毒矢",
        buyPrice: 100,
        sellPrice: 40,
        identificationStatus: "always",
    
    },
    {
        id: "4005",
        type: "arrow",
        name: "必中の矢",
        buyPrice: 120,
        sellPrice: 48,
        identificationStatus: "always",
    
    },
];

