// This file is generated by shiren6.py. Do not edit this file directly.
import type { Bracelet } from './definitions';

export const bracelets: readonly Bracelet[] = [
    {
        id: "3001",
        type: "bracelet",
        name: "回復の腕輪",
        buyPrice: 5000,
        sellPrice: 2000,
        identificationStatus: "never",
    
    },
    {
        id: "3002",
        type: "bracelet",
        name: "ちからの腕輪",
        buyPrice: 2000,
        sellPrice: 800,
        identificationStatus: "never",
    
    },
    {
        id: "3003",
        type: "bracelet",
        name: "胃拡張の腕輪",
        buyPrice: 3500,
        sellPrice: 1400,
        identificationStatus: "never",
    
    },
    {
        id: "3004",
        type: "bracelet",
        name: "胃縮小の腕輪",
        buyPrice: 3500,
        sellPrice: 1400,
        identificationStatus: "never",
    
    },
    {
        id: "3005",
        type: "bracelet",
        name: "しあわせの腕輪",
        buyPrice: 4000,
        sellPrice: 1600,
        identificationStatus: "never",
    
    },
    {
        id: "3006",
        type: "bracelet",
        name: "毒消し草の腕輪",
        buyPrice: 6500,
        sellPrice: 2600,
        identificationStatus: "never",
    
    },
    {
        id: "3007",
        type: "bracelet",
        name: "混乱よけの腕輪",
        buyPrice: 4000,
        sellPrice: 1600,
        identificationStatus: "never",
    
    },
    {
        id: "3008",
        type: "bracelet",
        name: "睡眠よけの腕輪",
        buyPrice: 2500,
        sellPrice: 1000,
        identificationStatus: "never",
    
    },
    {
        id: "3009",
        type: "bracelet",
        name: "錆よけの腕輪",
        buyPrice: 5000,
        sellPrice: 2000,
        identificationStatus: "never",
    
    },
    {
        id: "3010",
        type: "bracelet",
        name: "呪いよけの腕輪",
        buyPrice: 3000,
        sellPrice: 1200,
        identificationStatus: "never",
    
    },
    {
        id: "3011",
        type: "bracelet",
        name: "弾きよけの腕輪",
        buyPrice: 3500,
        sellPrice: 1400,
        identificationStatus: "never",
    
    },
    {
        id: "3012",
        type: "bracelet",
        name: "遠投の腕輪",
        buyPrice: 1500,
        sellPrice: 600,
        identificationStatus: "never",
    
    },
    {
        id: "3013",
        type: "bracelet",
        name: "ヘタ投げの腕輪",
        buyPrice: 1500,
        sellPrice: 600,
        identificationStatus: "never",
    
    },
    {
        id: "3014",
        type: "bracelet",
        name: "百発百中の腕輪",
        buyPrice: 15000,
        sellPrice: 6000,
        identificationStatus: "never",
    
    },
    {
        id: "3015",
        type: "bracelet",
        name: "ボヨヨンの腕輪",
        buyPrice: 1500,
        sellPrice: 600,
        identificationStatus: "never",
    
    },
    {
        id: "3016",
        type: "bracelet",
        name: "連射の腕輪",
        buyPrice: 1500,
        sellPrice: 600,
        identificationStatus: "never",
    
    },
    {
        id: "3017",
        type: "bracelet",
        name: "諸刃の腕輪",
        buyPrice: 1500,
        sellPrice: 600,
        identificationStatus: "never",
    
    },
    {
        id: "3018",
        type: "bracelet",
        name: "痛恨の腕輪",
        buyPrice: 1500,
        sellPrice: 600,
        identificationStatus: "never",
    
    },
    {
        id: "3019",
        type: "bracelet",
        name: "高飛びの腕輪",
        buyPrice: 1500,
        sellPrice: 600,
        identificationStatus: "never",
    
    },
    {
        id: "3020",
        type: "bracelet",
        name: "爆発の腕輪",
        buyPrice: 1500,
        sellPrice: 600,
        identificationStatus: "never",
    
    },
    {
        id: "3021",
        type: "bracelet",
        name: "透視の腕輪",
        buyPrice: 5000,
        sellPrice: 2000,
        identificationStatus: "never",
    
    },
    {
        id: "3022",
        type: "bracelet",
        name: "気配察知の腕輪",
        buyPrice: 2500,
        sellPrice: 1000,
        identificationStatus: "never",
    
    },
    {
        id: "3023",
        type: "bracelet",
        name: "道具感知の腕輪",
        buyPrice: 2500,
        sellPrice: 1000,
        identificationStatus: "never",
    
    },
    {
        id: "3024",
        type: "bracelet",
        name: "裏道の腕輪",
        buyPrice: 5000,
        sellPrice: 2000,
        identificationStatus: "never",
    
    },
    {
        id: "3025",
        type: "bracelet",
        name: "水グモの腕輪",
        buyPrice: 3000,
        sellPrice: 1200,
        identificationStatus: "never",
    
    },
    {
        id: "3026",
        type: "bracelet",
        name: "浮遊の腕輪",
        buyPrice: 3000,
        sellPrice: 1200,
        identificationStatus: "never",
    
    },
    {
        id: "3027",
        type: "bracelet",
        name: "壁抜けの腕輪",
        buyPrice: 6500,
        sellPrice: 2600,
        identificationStatus: "never",
    
    },
    {
        id: "3028",
        type: "bracelet",
        name: "忍び足の腕輪",
        buyPrice: 6500,
        sellPrice: 2600,
        identificationStatus: "never",
    
    },
    {
        id: "3029",
        type: "bracelet",
        name: "すれちがいの腕輪",
        buyPrice: 5000,
        sellPrice: 2000,
        identificationStatus: "never",
    
    },
    {
        id: "3030",
        type: "bracelet",
        name: "垂れ流しの腕輪",
        buyPrice: 1500,
        sellPrice: 600,
        identificationStatus: "never",
    
    },
    {
        id: "3031",
        type: "bracelet",
        name: "金垂れ流しの腕輪",
        buyPrice: 1500,
        sellPrice: 600,
        identificationStatus: "never",
    
    },
    {
        id: "3032",
        type: "bracelet",
        name: "魔物呼びの腕輪",
        buyPrice: 3000,
        sellPrice: 1200,
        identificationStatus: "never",
    
    },
    {
        id: "3033",
        type: "bracelet",
        name: "罠増しの腕輪",
        buyPrice: 1500,
        sellPrice: 600,
        identificationStatus: "never",
    
    },
    {
        id: "3034",
        type: "bracelet",
        name: "値切りの腕輪",
        buyPrice: 3500,
        sellPrice: 1400,
        identificationStatus: "never",
    
    },
    {
        id: "3035",
        type: "bracelet",
        name: "罠師の腕輪",
        buyPrice: 7500,
        sellPrice: 3000,
        identificationStatus: "never",
    
    },
    {
        id: "3036",
        type: "bracelet",
        name: "鑑定士の腕輪",
        buyPrice: 7500,
        sellPrice: 3000,
        identificationStatus: "never",
    
    },
    {
        id: "3037",
        type: "bracelet",
        name: "大砲強化の腕輪",
        buyPrice: 2500,
        sellPrice: 1000,
        identificationStatus: "never",
    
    },
];

