// This file is generated by shiren6.py. Do not edit this file directly.
import type { Food } from './definitions';

export const foods: readonly Food[] = [
    {
        id: "6001",
        type: "food",
        name: "おにぎり",
        buyPrice: 50,
        sellPrice: 20,
        identificationStatus: "always",
    
    },
    {
        id: "6002",
        type: "food",
        name: "大きいおにぎり",
        buyPrice: 150,
        sellPrice: 60,
        identificationStatus: "always",
    
    },
    {
        id: "6003",
        type: "food",
        name: "巨大なおにぎり",
        buyPrice: 400,
        sellPrice: 160,
        identificationStatus: "always",
    
    },
    {
        id: "6004",
        type: "food",
        name: "腐ったおにぎり",
        buyPrice: 10,
        sellPrice: 4,
        identificationStatus: "always",
    
    },
    {
        id: "6005",
        type: "food",
        name: "焼きおにぎり",
        buyPrice: 70,
        sellPrice: 28,
        identificationStatus: "always",
    
    },
    {
        id: "6006",
        type: "food",
        name: "特製おにぎり",
        buyPrice: 5000,
        sellPrice: 2000,
        identificationStatus: "always",
    
    },
    {
        id: "6007",
        type: "food",
        name: "ちゃんこおにぎり",
        buyPrice: 3000,
        sellPrice: 1200,
        identificationStatus: "always",
    
    },
    {
        id: "6008",
        type: "food",
        name: "ヤキイモ",
        buyPrice: 50,
        sellPrice: 20,
        identificationStatus: "always",
    
    },
    {
        id: "6009",
        type: "food",
        name: "ヤキトリ",
        buyPrice: 50,
        sellPrice: 25,
        identificationStatus: "always",
    
    },
    {
        id: "6010",
        type: "food",
        name: "腐った桃まん",
        buyPrice: 20,
        sellPrice: 8,
        identificationStatus: "always",
    
    },
];

