// This file is generated by shiren6.py. Do not edit this file directly.
import type { Grass } from './definitions';

export const grasses: readonly Grass[] = [
    {
        id: "7001",
        type: "grass",
        name: "雑草",
        buyPrice: 10,
        sellPrice: 4,
        identificationStatus: "always",
    
    },
    {
        id: "7002",
        type: "grass",
        name: "薬草",
        buyPrice: 40,
        sellPrice: 10,
        identificationStatus: "never",
    
    },
    {
        id: "7003",
        type: "grass",
        name: "弟切草",
        buyPrice: 80,
        sellPrice: 30,
        identificationStatus: "never",
    
    },
    {
        id: "7004",
        type: "grass",
        name: "いやし草",
        buyPrice: 200,
        sellPrice: 80,
        identificationStatus: "never",
    
    },
    {
        id: "7005",
        type: "grass",
        name: "命の草",
        buyPrice: 500,
        sellPrice: 200,
        identificationStatus: "never",
    
    },
    {
        id: "7006",
        type: "grass",
        name: "かぐわし草",
        buyPrice: 200,
        sellPrice: 80,
        identificationStatus: "never",
    
    },
    {
        id: "7007",
        type: "grass",
        name: "復活の草",
        buyPrice: 400,
        sellPrice: 160,
        identificationStatus: "never",
    
    },
    {
        id: "7008",
        type: "grass",
        name: "胃拡張の種",
        buyPrice: 200,
        sellPrice: 80,
        identificationStatus: "never",
    
    },
    {
        id: "7009",
        type: "grass",
        name: "胃縮小の種",
        buyPrice: 200,
        sellPrice: 80,
        identificationStatus: "never",
    
    },
    {
        id: "7010",
        type: "grass",
        name: "ドラゴン草",
        buyPrice: 250,
        sellPrice: 100,
        identificationStatus: "never",
    
    },
    {
        id: "7011",
        type: "grass",
        name: "高飛び草",
        buyPrice: 100,
        sellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "7012",
        type: "grass",
        name: "毒消し草",
        buyPrice: 600,
        sellPrice: 240,
        identificationStatus: "never",
    
    },
    {
        id: "7013",
        type: "grass",
        name: "ちからの草",
        buyPrice: 700,
        sellPrice: 280,
        identificationStatus: "never",
    
    },
    {
        id: "7014",
        type: "grass",
        name: "毒草",
        buyPrice: 50,
        sellPrice: 20,
        identificationStatus: "never",
    
    },
    {
        id: "7015",
        type: "grass",
        name: "混乱草",
        buyPrice: 70,
        sellPrice: 25,
        identificationStatus: "never",
    
    },
    {
        id: "7016",
        type: "grass",
        name: "睡眠草",
        buyPrice: 70,
        sellPrice: 25,
        identificationStatus: "never",
    
    },
    {
        id: "7017",
        type: "grass",
        name: "暴走の草",
        buyPrice: 50,
        sellPrice: 20,
        identificationStatus: "never",
    
    },
    {
        id: "7018",
        type: "grass",
        name: "目つぶし草",
        buyPrice: 70,
        sellPrice: 25,
        identificationStatus: "never",
    
    },
    {
        id: "7019",
        type: "grass",
        name: "めぐすり草",
        buyPrice: 70,
        sellPrice: 25,
        identificationStatus: "never",
    
    },
    {
        id: "7020",
        type: "grass",
        name: "すばやさ草",
        buyPrice: 70,
        sellPrice: 25,
        identificationStatus: "never",
    
    },
    {
        id: "7021",
        type: "grass",
        name: "パワーアップ草",
        buyPrice: 70,
        sellPrice: 25,
        identificationStatus: "never",
    
    },
    {
        id: "7022",
        type: "grass",
        name: "無敵草",
        buyPrice: 400,
        sellPrice: 160,
        identificationStatus: "never",
    
    },
    {
        id: "7023",
        type: "grass",
        name: "しあわせ草",
        buyPrice: 1000,
        sellPrice: 400,
        identificationStatus: "never",
    
    },
    {
        id: "7024",
        type: "grass",
        name: "天使の種",
        buyPrice: 2000,
        sellPrice: 800,
        identificationStatus: "never",
    
    },
    {
        id: "7025",
        type: "grass",
        name: "くねくね草",
        buyPrice: 100,
        sellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "7026",
        type: "grass",
        name: "不幸の種",
        buyPrice: 400,
        sellPrice: 160,
        identificationStatus: "never",
    
    },
    {
        id: "7027",
        type: "grass",
        name: "超不幸の種",
        buyPrice: 2000,
        sellPrice: 800,
        identificationStatus: "never",
    
    },
];

