// This file is generated by shiren6.py. Do not edit this file directly.
import type { Incense } from './definitions';

export const incenses: readonly Incense[] = [
    {
        id: "10001",
        type: "incense",
        name: "耐炎耐爆のお香",
        buyPrice: 2000,
        sellPrice: 800,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "10002",
        type: "incense",
        name: "身かわしのお香",
        buyPrice: 2000,
        sellPrice: 800,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "10003",
        type: "incense",
        name: "目配りのお香",
        buyPrice: 2000,
        sellPrice: 800,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "10004",
        type: "incense",
        name: "山彦のお香",
        buyPrice: 2000,
        sellPrice: 800,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "10005",
        type: "incense",
        name: "攻めのお香",
        buyPrice: 2000,
        sellPrice: 800,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "10006",
        type: "incense",
        name: "守りのお香",
        buyPrice: 2000,
        sellPrice: 800,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "10007",
        type: "incense",
        name: "視界不良のお香",
        buyPrice: 2000,
        sellPrice: 800,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "10008",
        type: "incense",
        name: "重力のお香",
        buyPrice: 2000,
        sellPrice: 800,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "10009",
        type: "incense",
        name: "無欲のお香",
        buyPrice: 2000,
        sellPrice: 800,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
];

