// This file is generated by shiren6.py. Do not edit this file directly.
import type { Pot } from './definitions';

export const pots: readonly Pot[] = [
    {
        id: "11001",
        type: "pot",
        name: "保存の壺",
        buyPrice: 800,
        sellPrice: 320,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "11002",
        type: "pot",
        name: "識別の壺",
        buyPrice: 800,
        sellPrice: 320,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "11003",
        type: "pot",
        name: "変化の壺",
        buyPrice: 800,
        sellPrice: 320,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "11004",
        type: "pot",
        name: "換金の壺",
        buyPrice: 1000,
        sellPrice: 400,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "11005",
        type: "pot",
        name: "合成の壺",
        buyPrice: 6000,
        sellPrice: 2400,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "11006",
        type: "pot",
        name: "おはらいの壺",
        buyPrice: 1600,
        sellPrice: 640,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "11007",
        type: "pot",
        name: "呪いの壺",
        buyPrice: 1600,
        sellPrice: 640,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "11008",
        type: "pot",
        name: "強化の壺",
        buyPrice: 10000,
        sellPrice: 4000,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "11009",
        type: "pot",
        name: "弱化の壺",
        buyPrice: 10000,
        sellPrice: 4000,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "11010",
        type: "pot",
        name: "底抜けの壺",
        buyPrice: 1000,
        sellPrice: 400,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "11011",
        type: "pot",
        name: "倉庫の壺",
        buyPrice: 1000,
        sellPrice: 400,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "11012",
        type: "pot",
        name: "手封じの壺",
        buyPrice: 1000,
        sellPrice: 400,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "11013",
        type: "pot",
        name: "割れない壺",
        buyPrice: 1000,
        sellPrice: 400,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "11014",
        type: "pot",
        name: "ただの壺",
        buyPrice: 800,
        sellPrice: 320,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "11015",
        type: "pot",
        name: "やりすごしの壺",
        buyPrice: 800,
        sellPrice: 320,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "11016",
        type: "pot",
        name: "背中の壺",
        buyPrice: 2000,
        sellPrice: 800,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "11017",
        type: "pot",
        name: "トドの壺",
        buyPrice: 2000,
        sellPrice: 800,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "11018",
        type: "pot",
        name: "水鉄砲の壺",
        buyPrice: 2000,
        sellPrice: 800,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "11019",
        type: "pot",
        name: "笑いの壺",
        buyPrice: 2000,
        sellPrice: 800,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "11020",
        type: "pot",
        name: "魔物の壺",
        buyPrice: 2000,
        sellPrice: 800,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "11021",
        type: "pot",
        name: "ビックリの壺",
        buyPrice: 2000,
        sellPrice: 800,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
    
    },
];

