// This file is generated by shiren6.py. Do not edit this file directly.
import type { Rock } from './definitions';

export const rocks: readonly Rock[] = [
    {
        id: "5001",
        type: "rock",
        name: "石",
        buyPrice: 10,
        sellPrice: 4,
        identificationStatus: "always",
    
    },
    {
        id: "5002",
        type: "rock",
        name: "デブータの石",
        buyPrice: 50,
        sellPrice: 20,
        identificationStatus: "always",
    
    },
];

