// This file is generated by shiren6.py. Do not edit this file directly.
import type { Scroll } from './definitions';

export const scrolls: readonly Scroll[] = [
    {
        id: "8001",
        type: "scroll",
        name: "混乱の巻物",
        buyPrice: 300,
        sellPrice: 120,
        identificationStatus: "never",
    
    },
    {
        id: "8002",
        type: "scroll",
        name: "バクスイの巻物",
        buyPrice: 300,
        sellPrice: 120,
        identificationStatus: "never",
    
    },
    {
        id: "8003",
        type: "scroll",
        name: "ゾワゾワの巻物",
        buyPrice: 300,
        sellPrice: 120,
        identificationStatus: "never",
    
    },
    {
        id: "8004",
        type: "scroll",
        name: "真空斬りの巻物",
        buyPrice: 300,
        sellPrice: 120,
        identificationStatus: "never",
    
    },
    {
        id: "8005",
        type: "scroll",
        name: "全滅の巻物",
        buyPrice: 3000,
        sellPrice: 1200,
        identificationStatus: "never",
    
    },
    {
        id: "8006",
        type: "scroll",
        name: "おはらいの巻物",
        buyPrice: 600,
        sellPrice: 240,
        identificationStatus: "never",
    
    },
    {
        id: "8007",
        type: "scroll",
        name: "識別の巻物",
        buyPrice: 300,
        sellPrice: 120,
        identificationStatus: "never",
    
    },
    {
        id: "8008",
        type: "scroll",
        name: "天の恵みの巻物",
        buyPrice: 400,
        sellPrice: 160,
        identificationStatus: "never",
    
    },
    {
        id: "8009",
        type: "scroll",
        name: "地の恵みの巻物",
        buyPrice: 400,
        sellPrice: 160,
        identificationStatus: "never",
    
    },
    {
        id: "8010",
        type: "scroll",
        name: "メッキの巻物",
        buyPrice: 400,
        sellPrice: 160,
        identificationStatus: "never",
    
    },
    {
        id: "8011",
        type: "scroll",
        name: "印増大の巻物",
        buyPrice: 400,
        sellPrice: 160,
        identificationStatus: "never",
    
    },
    {
        id: "8012",
        type: "scroll",
        name: "印消しの巻物",
        buyPrice: 400,
        sellPrice: 160,
        identificationStatus: "never",
    
    },
    {
        id: "8013",
        type: "scroll",
        name: "銀封印の巻物",
        buyPrice: 300,
        sellPrice: 120,
        identificationStatus: "never",
    
    },
    {
        id: "8014",
        type: "scroll",
        name: "銀はがしの巻物",
        buyPrice: 1000,
        sellPrice: 400,
        identificationStatus: "never",
    
    },
    {
        id: "8015",
        type: "scroll",
        name: "壺増大の巻物",
        buyPrice: 1000,
        sellPrice: 400,
        identificationStatus: "never",
    
    },
    {
        id: "8016",
        type: "scroll",
        name: "吸い出しの巻物",
        buyPrice: 1000,
        sellPrice: 400,
        identificationStatus: "never",
    
    },
    {
        id: "8017",
        type: "scroll",
        name: "おにぎりの巻物",
        buyPrice: 400,
        sellPrice: 160,
        identificationStatus: "never",
    
    },
    {
        id: "8018",
        type: "scroll",
        name: "呪いの巻物",
        buyPrice: 1000,
        sellPrice: 400,
        identificationStatus: "never",
    
    },
    {
        id: "8019",
        type: "scroll",
        name: "あかりの巻物",
        buyPrice: 600,
        sellPrice: 240,
        identificationStatus: "never",
    
    },
    {
        id: "8020",
        type: "scroll",
        name: "迷子の巻物",
        buyPrice: 600,
        sellPrice: 240,
        identificationStatus: "never",
    
    },
    {
        id: "8021",
        type: "scroll",
        name: "罠消しの巻物",
        buyPrice: 600,
        sellPrice: 240,
        identificationStatus: "never",
    
    },
    {
        id: "8022",
        type: "scroll",
        name: "罠の巻物",
        buyPrice: 1000,
        sellPrice: 400,
        identificationStatus: "never",
    
    },
    {
        id: "8023",
        type: "scroll",
        name: "水がれの巻物",
        buyPrice: 1000,
        sellPrice: 400,
        identificationStatus: "never",
    
    },
    {
        id: "8024",
        type: "scroll",
        name: "魔物部屋の巻物",
        buyPrice: 1000,
        sellPrice: 400,
        identificationStatus: "never",
    
    },
    {
        id: "8025",
        type: "scroll",
        name: "大部屋の巻物",
        buyPrice: 1000,
        sellPrice: 400,
        identificationStatus: "never",
    
    },
    {
        id: "8026",
        type: "scroll",
        name: "生物集合の巻物",
        buyPrice: 300,
        sellPrice: 120,
        identificationStatus: "never",
    
    },
    {
        id: "8027",
        type: "scroll",
        name: "道具よせの巻物",
        buyPrice: 300,
        sellPrice: 120,
        identificationStatus: "never",
    
    },
    {
        id: "8028",
        type: "scroll",
        name: "バクチの巻物",
        buyPrice: 1000,
        sellPrice: 400,
        identificationStatus: "never",
    
    },
    {
        id: "8029",
        type: "scroll",
        name: "くちなしの巻物",
        buyPrice: 1000,
        sellPrice: 400,
        identificationStatus: "never",
    
    },
    {
        id: "8030",
        type: "scroll",
        name: "拾えずの巻物",
        buyPrice: 1000,
        sellPrice: 400,
        identificationStatus: "never",
    
    },
    {
        id: "8031",
        type: "scroll",
        name: "敵加速の巻物",
        buyPrice: 1000,
        sellPrice: 400,
        identificationStatus: "never",
    
    },
    {
        id: "8032",
        type: "scroll",
        name: "困った時の巻物",
        buyPrice: 300,
        sellPrice: 120,
        identificationStatus: "never",
    
    },
    {
        id: "8033",
        type: "scroll",
        name: "脱出の巻物",
        buyPrice: 1000,
        sellPrice: 400,
        identificationStatus: "never",
    
    },
    {
        id: "8034",
        type: "scroll",
        name: "ねだやしの巻物",
        buyPrice: 10000,
        sellPrice: 4000,
        identificationStatus: "never",
    
    },
    {
        id: "8035",
        type: "scroll",
        name: "聖域の巻物",
        buyPrice: 1000,
        sellPrice: 400,
        identificationStatus: "never",
    
    },
    {
        id: "8036",
        type: "scroll",
        name: "白紙の巻物",
        buyPrice: 1000,
        sellPrice: 400,
        identificationStatus: "never",
    
    },
    {
        id: "8037",
        type: "scroll",
        name: "ぬれた巻物",
        buyPrice: 200,
        sellPrice: 80,
        identificationStatus: "always",
    
    },
];

