// This file is generated by shiren6.py. Do not edit this file directly.
import type { Shield } from './definitions';

export const shields: readonly Shield[] = [
    {
        id: "2001",
        type: "shield",
        name: "木甲の盾",
        defense: 3,
        runeCount: 7,
        buyPrice: 500,
        sellPrice: 200,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
        resonanceIds: [
            '1001', // 木刀
        ],
    
    },
    {
        id: "2002",
        type: "shield",
        name: "青銅甲の盾",
        defense: 4,
        runeCount: 6,
        buyPrice: 800,
        sellPrice: 320,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
        resonanceIds: [
            '1002', // 青銅の太刀
        ],
    
    },
    {
        id: "2003",
        type: "shield",
        name: "鉄甲の盾",
        defense: 6,
        runeCount: 5,
        buyPrice: 1200,
        sellPrice: 480,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
        resonanceIds: [
            '1003', // カタナ
        ],
    
    },
    {
        id: "2004",
        type: "shield",
        name: "おにおおかみ",
        defense: 8,
        runeCount: 4,
        buyPrice: 1500,
        sellPrice: 600,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
        resonanceIds: [
            '1004', // どうたぬき
        ],
    
    },
    {
        id: "2005",
        type: "shield",
        name: "風魔の盾",
        defense: 13,
        runeCount: 3,
        buyPrice: 6000,
        sellPrice: 2400,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
        resonanceIds: [
            '1005', // 剛剣マンジカブラ
            '1006', // 火迅風魔刀
            '1007', // 秘剣カブラステギ
        ],
    
    },
    {
        id: "2006",
        type: "shield",
        name: "螺旋風魔の盾",
        defense: 30,
        runeCount: 15,
        buyPrice: 15000,
        sellPrice: 6000,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
        resonanceIds: [
            '1005', // 剛剣マンジカブラ
            '1006', // 火迅風魔刀
            '1007', // 秘剣カブラステギ
        ],
    
    },
    {
        id: "2007",
        type: "shield",
        name: "金の盾",
        defense: 4,
        runeCount: 10,
        buyPrice: 2500,
        sellPrice: 1000,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
        resonanceIds: [
            '1008', // 金の剣
        ],
    
    },
    {
        id: "2008",
        type: "shield",
        name: "バトルカウンター",
        defense: 2,
        runeCount: 6,
        buyPrice: 2200,
        sellPrice: 880,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
    
    
    },
    {
        id: "2009",
        type: "shield",
        name: "見切りの盾",
        defense: 1,
        runeCount: 5,
        buyPrice: 4000,
        sellPrice: 1600,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
        resonanceIds: [
            '1020', // 一ツ目殺し
        ],
    
    },
    {
        id: "2010",
        type: "shield",
        name: "ドラゴンシールド",
        defense: 7,
        runeCount: 5,
        buyPrice: 3000,
        sellPrice: 1200,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
        resonanceIds: [
            '1015', // ドラゴンキラー
        ],
    
    },
    {
        id: "2011",
        type: "shield",
        name: "爆発隠の盾",
        defense: 6,
        runeCount: 4,
        buyPrice: 3300,
        sellPrice: 1320,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
        resonanceIds: [
            '1016', // 三日月刀
        ],
    
    },
    {
        id: "2012",
        type: "shield",
        name: "ミノタウロスの盾",
        defense: 7,
        runeCount: 5,
        buyPrice: 2500,
        sellPrice: 1000,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
        resonanceIds: [
            '1010', // ミノタウロスの斧
        ],
    
    },
    {
        id: "2013",
        type: "shield",
        name: "トドよけの盾",
        defense: 4,
        runeCount: 5,
        buyPrice: 2600,
        sellPrice: 1040,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
    
    
    },
    {
        id: "2014",
        type: "shield",
        name: "ガマラよけの盾",
        defense: 5,
        runeCount: 6,
        buyPrice: 2700,
        sellPrice: 1080,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
    
    
    },
    {
        id: "2015",
        type: "shield",
        name: "いたずらよけの盾",
        defense: 6,
        runeCount: 3,
        buyPrice: 2800,
        sellPrice: 1120,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
    
    
    },
    {
        id: "2016",
        type: "shield",
        name: "にぎりよけの盾",
        defense: 3,
        runeCount: 5,
        buyPrice: 3600,
        sellPrice: 1440,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
    
    
    },
    {
        id: "2017",
        type: "shield",
        name: "オトトの盾",
        defense: 5,
        runeCount: 6,
        buyPrice: 2000,
        sellPrice: 800,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
        resonanceIds: [
            '1013', // 水斬りの剣
        ],
    
    },
    {
        id: "2018",
        type: "shield",
        name: "カッパのお皿",
        defense: 4,
        runeCount: 7,
        buyPrice: 5000,
        sellPrice: 2000,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
    
    
    },
    {
        id: "2019",
        type: "shield",
        name: "ゲイズの盾",
        defense: 3,
        runeCount: 5,
        buyPrice: 4000,
        sellPrice: 1600,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
    
    
    },
    {
        id: "2020",
        type: "shield",
        name: "魔法よけの盾",
        defense: 2,
        runeCount: 3,
        buyPrice: 7500,
        sellPrice: 3000,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
    
    
    },
    {
        id: "2021",
        type: "shield",
        name: "不動の盾",
        defense: 6,
        runeCount: 5,
        buyPrice: 2500,
        sellPrice: 1000,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
    
    
    },
    {
        id: "2022",
        type: "shield",
        name: "ざぶとん",
        defense: 7,
        runeCount: 5,
        buyPrice: 3000,
        sellPrice: 1200,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
        resonanceIds: [
            '1022', // 巨大ハリセン
        ],
    
    },
    {
        id: "2023",
        type: "shield",
        name: "金食い虫の盾",
        defense: 8,
        runeCount: 4,
        buyPrice: 6000,
        sellPrice: 2400,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
        resonanceIds: [
            '1025', // 金食い虫こん棒
        ],
    
    },
    {
        id: "2024",
        type: "shield",
        name: "鉄塊の大盾",
        defense: 9,
        runeCount: 3,
        buyPrice: 4400,
        sellPrice: 1760,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
        resonanceIds: [
            '1026', // 鉄塊の大剣
        ],
    
    },
    {
        id: "2025",
        type: "shield",
        name: "ステーキプレート",
        defense: 7,
        runeCount: 5,
        buyPrice: 4500,
        sellPrice: 1800,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
        resonanceIds: [
            '1027', // ステーキナイフ
        ],
    
    },
    {
        id: "2026",
        type: "shield",
        name: "根性の盾",
        defense: 9,
        runeCount: 4,
        buyPrice: 4600,
        sellPrice: 1840,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
    
    
    },
    {
        id: "2027",
        type: "shield",
        name: "絶好調の盾",
        defense: 5,
        runeCount: 3,
        buyPrice: 5000,
        sellPrice: 2000,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
    
    
    },
    {
        id: "2028",
        type: "shield",
        name: "サトリの盾",
        defense: 3,
        runeCount: 6,
        buyPrice: 10000,
        sellPrice: 4000,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
    
    
    },
    {
        id: "2029",
        type: "shield",
        name: "ハラモチの盾",
        defense: 2,
        runeCount: 5,
        buyPrice: 2000,
        sellPrice: 800,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
        resonanceIds: [
            '1036', // かつおぶし
        ],
    
    },
    {
        id: "2030",
        type: "shield",
        name: "めでたい御守",
        defense: 7,
        runeCount: 7,
        buyPrice: 5500,
        sellPrice: 2200,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
        resonanceIds: [
            '1030', // めでたい熊手
        ],
    
    },
    {
        id: "2031",
        type: "shield",
        name: "お告げの盾",
        defense: 5,
        runeCount: 5,
        buyPrice: 7000,
        sellPrice: 2800,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
    
    
    },
    {
        id: "2032",
        type: "shield",
        name: "山姥の鍋ぶた",
        defense: 10,
        runeCount: 7,
        buyPrice: 4100,
        sellPrice: 1640,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
        resonanceIds: [
            '1037', // 山姥包丁
        ],
    
    },
    {
        id: "2033",
        type: "shield",
        name: "使い捨ての盾",
        defense: 30,
        runeCount: 10,
        buyPrice: 3400,
        sellPrice: 1360,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
        resonanceIds: [
            '1038', // 使い捨て刀
        ],
    
    },
];

