// This file is generated by shiren6.py. Do not edit this file directly.
import type { Staff } from './definitions';

export const staffs: readonly Staff[] = [
    {
        id: "9001",
        type: "staff",
        name: "ただの杖",
        buyPrice: 500,
        sellPrice: 200,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "9002",
        type: "staff",
        name: "かなしばりの杖",
        buyPrice: 500,
        sellPrice: 200,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "9003",
        type: "staff",
        name: "封印の杖",
        buyPrice: 500,
        sellPrice: 200,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "9004",
        type: "staff",
        name: "身代わりの杖",
        buyPrice: 2000,
        sellPrice: 800,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "9005",
        type: "staff",
        name: "痛み分けの杖",
        buyPrice: 1000,
        sellPrice: 400,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "9006",
        type: "staff",
        name: "一時しのぎの杖",
        buyPrice: 1000,
        sellPrice: 400,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "9007",
        type: "staff",
        name: "吹き飛ばしの杖",
        buyPrice: 500,
        sellPrice: 200,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "9008",
        type: "staff",
        name: "場所がえの杖",
        buyPrice: 500,
        sellPrice: 200,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "9009",
        type: "staff",
        name: "飛びつきの杖",
        buyPrice: 500,
        sellPrice: 200,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "9010",
        type: "staff",
        name: "ガイコツまどうの杖",
        buyPrice: 1000,
        sellPrice: 400,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "9011",
        type: "staff",
        name: "感電の杖",
        buyPrice: 500,
        sellPrice: 200,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "9012",
        type: "staff",
        name: "トンネルの杖",
        buyPrice: 700,
        sellPrice: 280,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "9013",
        type: "staff",
        name: "土塊の杖",
        buyPrice: 700,
        sellPrice: 280,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "9014",
        type: "staff",
        name: "転ばぬ先の杖",
        buyPrice: 500,
        sellPrice: 200,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "9015",
        type: "staff",
        name: "導きの杖",
        buyPrice: 700,
        sellPrice: 280,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "9016",
        type: "staff",
        name: "加速の杖",
        buyPrice: 700,
        sellPrice: 280,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "9017",
        type: "staff",
        name: "鈍足の杖",
        buyPrice: 700,
        sellPrice: 280,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "9018",
        type: "staff",
        name: "幸せの杖",
        buyPrice: 1000,
        sellPrice: 400,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "9018",
        type: "staff",
        name: "不幸の杖",
        buyPrice: 1000,
        sellPrice: 400,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
    {
        id: "9019",
        type: "staff",
        name: "桃まんの杖",
        buyPrice: 2000,
        sellPrice: 800,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "never",
    
    },
];

