// This file is generated by shiren6.py. Do not edit this file directly.
import type { Weapon } from './definitions';

export const weapons: readonly Weapon[] = [
    {
        id: "1001",
        type: "weapon",
        name: "木刀",
        attack: 3,
        runeCount: 7,
        buyPrice: 250,
        sellPrice: 100,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
        resonanceIds: [
            '2001', // 木甲の盾
        ],
    
    },
    {
        id: "1002",
        type: "weapon",
        name: "青銅の太刀",
        attack: 4,
        runeCount: 6,
        buyPrice: 550,
        sellPrice: 220,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
        resonanceIds: [
            '2002', // 青銅甲の盾
        ],
    
    },
    {
        id: "1003",
        type: "weapon",
        name: "カタナ",
        attack: 5,
        runeCount: 5,
        buyPrice: 1000,
        sellPrice: 400,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
        resonanceIds: [
            '2003', // 鉄甲の盾
        ],
    
    },
    {
        id: "1004",
        type: "weapon",
        name: "どうたぬき",
        attack: 8,
        runeCount: 4,
        buyPrice: 2200,
        sellPrice: 880,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
        resonanceIds: [
            '2004', // おにおおかみ
        ],
    
    },
    {
        id: "1005",
        type: "weapon",
        name: "剛剣マンジカブラ",
        attack: 14,
        runeCount: 3,
        buyPrice: 5500,
        sellPrice: 2200,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
        resonanceIds: [
            '2005', // 風魔の盾
            '2006', // 螺旋風魔の盾
        ],
    
    },
    {
        id: "1006",
        type: "weapon",
        name: "火迅風魔刀",
        attack: 30,
        runeCount: 10,
        buyPrice: 16000,
        sellPrice: 6400,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
        resonanceIds: [
            '2005', // 風魔の盾
            '2006', // 螺旋風魔の盾
        ],
    
    },
    {
        id: "1007",
        type: "weapon",
        name: "秘剣カブラステギ",
        attack: 50,
        runeCount: 15,
        buyPrice: 25000,
        sellPrice: 10000,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
        resonanceIds: [
            '2005', // 風魔の盾
            '2006', // 螺旋風魔の盾
        ],
    
    },
    {
        id: "1008",
        type: "weapon",
        name: "金の剣",
        attack: 3,
        runeCount: 10,
        buyPrice: 3000,
        sellPrice: 1200,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
        resonanceIds: [
            '2007', // 金の盾
        ],
    
    },
    {
        id: "1009",
        type: "weapon",
        name: "妖刀かまいたち",
        attack: 2,
        runeCount: 6,
        buyPrice: 8400,
        sellPrice: 3360,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
    
    
    },
    {
        id: "1010",
        type: "weapon",
        name: "ミノタウロスの斧",
        attack: 6,
        runeCount: 4,
        buyPrice: 6500,
        sellPrice: 2600,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
        resonanceIds: [
            '2012', // ミノタウロスの盾
        ],
    
    },
    {
        id: "1012",
        type: "weapon",
        name: "連撃刀",
        attack: 5,
        runeCount: 3,
        buyPrice: 10000,
        sellPrice: 4000,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
    
    
    },
    {
        id: "1013",
        type: "weapon",
        name: "水斬りの剣",
        attack: 6,
        runeCount: 6,
        buyPrice: 3300,
        sellPrice: 1320,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
        resonanceIds: [
            '2017', // オトトの盾
        ],
    
    },
    {
        id: "1014",
        type: "weapon",
        name: "原始の斧",
        attack: 6,
        runeCount: 8,
        buyPrice: 5000,
        sellPrice: 2000,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
    
    
    },
    {
        id: "1015",
        type: "weapon",
        name: "ドラゴンキラー",
        attack: 9,
        runeCount: 5,
        buyPrice: 4000,
        sellPrice: 1600,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
        resonanceIds: [
            '2010', // ドラゴンシールド
        ],
    
    },
    {
        id: "1016",
        type: "weapon",
        name: "三日月刀",
        attack: 6,
        runeCount: 6,
        buyPrice: 3500,
        sellPrice: 1400,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
        resonanceIds: [
            '2011', // 爆発隠の盾
        ],
    
    },
    {
        id: "1017",
        type: "weapon",
        name: "空の刃",
        attack: 4,
        runeCount: 4,
        buyPrice: 3700,
        sellPrice: 1480,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
    
    
    },
    {
        id: "1018",
        type: "weapon",
        name: "成仏のカマ",
        attack: 5,
        runeCount: 8,
        buyPrice: 4200,
        sellPrice: 1680,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
    
    
    },
    {
        id: "1019",
        type: "weapon",
        name: "ドレインバスター",
        attack: 6,
        runeCount: 3,
        buyPrice: 3600,
        sellPrice: 1440,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
    
    
    },
    {
        id: "1020",
        type: "weapon",
        name: "一ツ目殺し",
        attack: 7,
        runeCount: 4,
        buyPrice: 3200,
        sellPrice: 1280,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
        resonanceIds: [
            '2009', // 見切りの盾
        ],
    
    },
    {
        id: "1021",
        type: "weapon",
        name: "斬鉄剣",
        attack: 6,
        runeCount: 5,
        buyPrice: 3100,
        sellPrice: 1240,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
    
    
    },
    {
        id: "1022",
        type: "weapon",
        name: "巨大ハリセン",
        attack: 5,
        runeCount: 4,
        buyPrice: 4200,
        sellPrice: 1680,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
        resonanceIds: [
            '2022', // ざぶとん
        ],
    
    },
    {
        id: "1023",
        type: "weapon",
        name: "回復の剣",
        attack: 2,
        runeCount: 4,
        buyPrice: 4300,
        sellPrice: 1720,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
    
    
    },
    {
        id: "1024",
        type: "weapon",
        name: "桃まん棒",
        attack: 4,
        runeCount: 3,
        buyPrice: 4500,
        sellPrice: 1800,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
    
    
    },
    {
        id: "1025",
        type: "weapon",
        name: "金食い虫こん棒",
        attack: 8,
        runeCount: 4,
        buyPrice: 6000,
        sellPrice: 2400,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
        resonanceIds: [
            '2023', // 金食い虫の盾
        ],
    
    },
    {
        id: "1026",
        type: "weapon",
        name: "鉄塊の大剣",
        attack: 9,
        runeCount: 3,
        buyPrice: 5300,
        sellPrice: 2120,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
        resonanceIds: [
            '2024', // 鉄塊の大盾
        ],
    
    },
    {
        id: "1027",
        type: "weapon",
        name: "ステーキナイフ",
        attack: 7,
        runeCount: 5,
        buyPrice: 5400,
        sellPrice: 2160,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
        resonanceIds: [
            '2025', // ステーキプレート
        ],
    
    },
    {
        id: "1028",
        type: "weapon",
        name: "スパークソード",
        attack: 4,
        runeCount: 6,
        buyPrice: 5500,
        sellPrice: 2200,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
    
    
    },
    {
        id: "1029",
        type: "weapon",
        name: "四ツ叉",
        attack: 6,
        runeCount: 4,
        buyPrice: 5600,
        sellPrice: 2240,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
    
    
    },
    {
        id: "1030",
        type: "weapon",
        name: "めでたい熊手",
        attack: 7,
        runeCount: 7,
        buyPrice: 5700,
        sellPrice: 2280,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
        resonanceIds: [
            '2030', // めでたい御守
        ],
    
    },
    {
        id: "1031",
        type: "weapon",
        name: "つるはし",
        attack: 8,
        runeCount: 1,
        buyPrice: 1000,
        sellPrice: 400,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
    
    
    },
    {
        id: "1032",
        type: "weapon",
        name: "黄金のつるはし",
        attack: 2,
        runeCount: 10,
        buyPrice: 18000,
        sellPrice: 7200,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
    
    
    },
    {
        id: "1033",
        type: "weapon",
        name: "木づち",
        attack: 7,
        runeCount: 3,
        buyPrice: 1000,
        sellPrice: 400,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
    
    
    },
    {
        id: "1034",
        type: "weapon",
        name: "最強ハンマー",
        attack: 2,
        runeCount: 5,
        buyPrice: 15000,
        sellPrice: 6000,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
    
    
    },
    {
        id: "1035",
        type: "weapon",
        name: "罠探りの棒",
        attack: 4,
        runeCount: 5,
        buyPrice: 4400,
        sellPrice: 1760,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
    
    
    },
    {
        id: "1036",
        type: "weapon",
        name: "かつおぶし",
        attack: 6,
        runeCount: 6,
        buyPrice: 1800,
        sellPrice: 720,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
        resonanceIds: [
            '2029', // ハラモチの盾
        ],
    
    },
    {
        id: "1037",
        type: "weapon",
        name: "山姥包丁",
        attack: 10,
        runeCount: 7,
        buyPrice: 4000,
        sellPrice: 1600,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
        resonanceIds: [
            '2032', // 山姥の鍋ぶた
        ],
    
    },
    {
        id: "1038",
        type: "weapon",
        name: "使い捨て刀",
        attack: 30,
        runeCount: 10,
        buyPrice: 3000,
        sellPrice: 1200,
        plusBuyPrice: 100,
        plusSellPrice: 40,
        identificationStatus: "always",
        resonanceIds: [
            '2033', // 使い捨ての盾
        ],
    
    },
];

